version: '3.5'

services:
  postgres:
    hostname: db.blog-service
    container_name: block-service-db-fastApi
    image: postgres
    env_file:
      - ./env/postgres-local.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure

volumes:
  postgres: